name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug",]
assignees:
  - KelvinPompey
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: new-bug
    attributes:
        label: Is there an existing issue for this?
        description: Please search to see if an issue already exists for the bug you encountered.
        options:
          - label: I have searched the existing issues
            required: true
  - type: input
    id: contact
    attributes:
      label: Contact Name
      description: How can we get in touch with you if we need more info?
      placeholder: ex. full name
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Description of the bug?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - Master Branch
        - Develop Branch
        - Feature Branch
      default: 0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Steps to Reproduce the Error
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/KelvinPompey-40718390/sem-project-group6/blob/master/CODE-OF-CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
