@startuml

actor E as "Employee"

rectangle Database

rectangle "Population Report" {
    usecase UC8 as "Get All the cities in a continent organised by largest population to smallest"

    usecase UCa as "Print Cities"

    E - UC8
    UC8 ..> UCa : include
    UC8 - Database
}

@enduml