@startuml

actor E as "Employee"

rectangle Database

rectangle "Population Report" {
    usecase UC7 as "Get All the cities in the world organised by largest population to smallest"

    usecase UCa as "Print Cities"

    E - UC7
    UC7 ..> UCa : include
    UC7 - Database
}

@enduml