@startuml
left to right direction
actor E as "Employee"

rectangle "Population Report System" {

    usecase UC11 as "Get cities in a district
    by largest to smallest population"

    usecase UC11a as "Print cities"

    usecase UC14 as "Get top N populated cities per region"

    usecase UC14b as "Input N"
    usecase UC14a as "Print top N populated cities per region"
}
rectangle Database

E --> UC14b
UC14b ..> UC14 : include

UC14 ..> UC14a : include
UC14 --> Database

E --> UC11
UC11 ..> UC11a : include
UC11 --> Database

@enduml