name: A workflow for sem Project Group 6 App
on: push

jobs:
  build:
    name: Functionality test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Compile with Maven
        run: mvn compile
      - name: Build Docker Image
        run: docker build -t group6image .
      - name: Run image
        run: docker run --name group6container -d group6image
      - name: view logs
        run: docker logs group6container
