name: A workflow for Group 6 App
on: push

jobs:
  build:
    name: Basic Functionality Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Compile with Maven
        run: mvn package
      - name: Build
        run: docker build -t seProjectGroup6-0.1.0.1-jar-with-dependencies.jar .
      - name: Run image
        run: docker run --name group6container -d seProjectGroup6-0.1.0.1-jar-with-dependencies.jar
      - name: view logs
        run: docker logs group6container
